'''Validator pipeline models and orchestration package.'''

from nexus.core.validator.pipeline_models import (
    DEFAULT_VALIDATION_STAGE_ORDER,
    ValidationAction,
    ValidationDecision,
    ValidationRequestContext,
    ValidationStage,
)
from nexus.core.validator.pipeline_executor import StageValidator, ValidationPipeline
from nexus.core.validator.intake_stage import (
    IntakeValidationHook,
    build_default_intake_hooks,
    make_duplicate_order_hook,
    make_order_rate_hook,
    make_reference_integrity_hook,
    validate_intake_stage,
)
from nexus.core.validator.risk_stage import (
    RiskStageLimits,
    evaluate_risk_breach,
    validate_risk_stage,
)
from nexus.core.validator.price_stage import (
    PriceCheckSnapshot,
    PriceFailureConsequence,
    PriceStageLimits,
    derive_price_failure_consequence,
    validate_price_stage,
)
from nexus.core.validator.capital_stage import (
    CAPITAL_RESERVATION_DENIED_CODE,
    validate_capital_stage,
)
from nexus.core.validator.platform_limits_stage import (
    PLATFORM_LIMITS_DAILY_LOSS_LIMIT_CODE,
    PLATFORM_LIMITS_MAX_CAPITAL_UTILIZATION_LIMIT_CODE,
    PLATFORM_LIMITS_MAX_ORDER_NOTIONAL_LIMIT_CODE,
    PLATFORM_LIMITS_MAX_ORDER_RATE_LIMIT_CODE,
    PLATFORM_LIMITS_MAX_POSITION_LIMIT_CODE,
    PLATFORM_LIMITS_SNAPSHOT_MISSING_CODE,
    PlatformLimitsStageLimits,
    PlatformLimitsStageSnapshot,
    validate_platform_limits_stage,
)
from nexus.core.validator.health_stage import (
    HEALTH_CLOCK_DRIFT_BREACH_CODE,
    HEALTH_CLOCK_DRIFT_HALT_CODE,
    HEALTH_CONSECUTIVE_FAILURES_BREACH_CODE,
    HEALTH_CONSECUTIVE_FAILURES_HALT_CODE,
    HEALTH_FAILURE_RATE_BREACH_CODE,
    HEALTH_FAILURE_RATE_HALT_CODE,
    HEALTH_LATENCY_BREACH_CODE,
    HEALTH_LATENCY_HALT_CODE,
    HEALTH_RATE_LIMIT_HEADROOM_BREACH_CODE,
    HEALTH_RATE_LIMIT_HEADROOM_HALT_CODE,
    HealthMetricThresholds,
    HealthStagePolicy,
    HealthStageSnapshot,
    evaluate_health_status,
    validate_health_stage,
)

__all__ = [
    'CAPITAL_RESERVATION_DENIED_CODE',
    'DEFAULT_VALIDATION_STAGE_ORDER',
    'HEALTH_CLOCK_DRIFT_BREACH_CODE',
    'HEALTH_CLOCK_DRIFT_HALT_CODE',
    'HEALTH_CONSECUTIVE_FAILURES_BREACH_CODE',
    'HEALTH_CONSECUTIVE_FAILURES_HALT_CODE',
    'HEALTH_FAILURE_RATE_BREACH_CODE',
    'HEALTH_FAILURE_RATE_HALT_CODE',
    'HEALTH_LATENCY_BREACH_CODE',
    'HEALTH_LATENCY_HALT_CODE',
    'HEALTH_RATE_LIMIT_HEADROOM_BREACH_CODE',
    'HEALTH_RATE_LIMIT_HEADROOM_HALT_CODE',
    'PLATFORM_LIMITS_DAILY_LOSS_LIMIT_CODE',
    'PLATFORM_LIMITS_MAX_CAPITAL_UTILIZATION_LIMIT_CODE',
    'PLATFORM_LIMITS_MAX_ORDER_NOTIONAL_LIMIT_CODE',
    'PLATFORM_LIMITS_MAX_ORDER_RATE_LIMIT_CODE',
    'PLATFORM_LIMITS_MAX_POSITION_LIMIT_CODE',
    'PLATFORM_LIMITS_SNAPSHOT_MISSING_CODE',
    'HealthMetricThresholds',
    'HealthStagePolicy',
    'HealthStageSnapshot',
    'IntakeValidationHook',
    'PlatformLimitsStageLimits',
    'PlatformLimitsStageSnapshot',
    'PriceCheckSnapshot',
    'PriceFailureConsequence',
    'PriceStageLimits',
    'RiskStageLimits',
    'StageValidator',
    'ValidationAction',
    'ValidationDecision',
    'ValidationPipeline',
    'ValidationRequestContext',
    'ValidationStage',
    'build_default_intake_hooks',
    'derive_price_failure_consequence',
    'evaluate_health_status',
    'evaluate_risk_breach',
    'make_duplicate_order_hook',
    'make_order_rate_hook',
    'make_reference_integrity_hook',
    'validate_capital_stage',
    'validate_health_stage',
    'validate_intake_stage',
    'validate_platform_limits_stage',
    'validate_price_stage',
    'validate_risk_stage',
]
